.

diff --git a/cloudformation/main.yml b/cloudformation/main.yml
--- a/cloudformation/main.yml
+++ b/cloudformation/main.yml
@@ -24,6 +24,7 @@ Resources:
       VpcId: !Ref StackVPC
       CidrBlock: 10.121.0.0/24
       AvailabilityZone: "eu-central-1a"
+      MapPublicIpOnLaunch: true
       Tags:
       - Key: stack
         Value: production
@@ -86,7 +87,7 @@ Resources:
         # This tells CloudFormation to wait for a signal before marking the new
         # instance as created (we’ll see how in the install script).
         # Timeout: PT15M
-        Timeout: PT3M
+        Timeout: PT15M
         Count: 1
     # Metadata:
     #   AWS::CloudFormation::Init:
@@ -103,8 +104,59 @@ Resources:
       SubnetId: !Ref StackSubnet
       SecurityGroupIds:
         - !Ref SecurityGroup
-      # UserData:
-      #   # ... 
+      UserData:
+        Fn::Base64: !Sub |
+          #!/bin/bash -xe
+
+          # send script output to /tmp so we can debug boot failures
+          exec > /tmp/userdata.log 2>&1
+
+          # Update all packages
+          yum -y update
+
+          # Get latest cfn scripts;
+          https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/bestpractices.html#cfninit
+
+          yum install -y aws-cfn-bootstrap
+          yum install -y git
+
+          # Have CloudFormation install any files and packages from the metadata
+          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource EC2Instance
+
+          cat > /tmp/install_script.sh << EOF
+          # START
+          echo "Setting up NodeJS Environment"
+          curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
+
+          # Dot source the files to ensure that variables are available within
+          the current shell
+          . /home/ec2-user/.nvm/nvm.sh
+          . /home/ec2-user/.bashrc
+
+          # Install NVM, NPM, Node.JS
+          nvm alias default v12.7.0
+          nvm install v12.7.0
+          nvm use v12.7.0
+
+          # Download latest code, unzip it into /home/ec2-user/app
+          wget https://github.com/rrralf/aws-bootstrap/archive/refs/heads/main.zip
+          unzip main.zip
+          mv aws-bootstrap-main app
+          # Create log directory
+          mkdir -p /home/ec2-user/app/logs
+          # Run server
+          cd app
+          npm install
+          npm start
+          EOF
+
+          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x
+          /tmp/install_script.sh
+
+          sleep 1; su - ec2-user -c "/tmp/install_script.sh"
+
+          # Signal to CloudFormation that the instance is ready
+          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource EC2Instance
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
